# author C.Panse
name: R-CMD-check-prolfqua
env:
    ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    R_LIBS_SITE: '/home/runner/work/_temp/Library/'
on:
  push:
    branches: [ Modelling2R6 ]
  pull_request:
    branches: [ Modelling2R6 ]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        r-version: [4.1.0]
    steps:
      - uses: actions/checkout@v2

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install Linux packages
        run: sudo apt-get install -y curl libcurl4-openssl-dev libicu-dev pandoc wget unzip texlive texlive-latex-extra texlive-fonts-extra texlive-xetex pandoc-citeproc lmodern
      - name: Cache R packages
        id: cache-rpkgs
        uses: actions/cache@v2
        with:
            path: ~/work/_temp/Library/
            key: ${{ runner.os }}-RpkgsV3-prolfqua

      - name: Install required R packages from CRAN and Bioconductor
        if: steps.cache-rpkgsV2.outputs.cache-hit != 'true'
        run: |
          install.packages(c('BiocManager', 'remotes', 'rmarkdown', 'roxygen2', 'testthat', 'rcmdcheck'), repos='https://cloud.r-project.org');
          pkgs <- c('DT', 'GGally', 'KernSmooth', 'MASS');
          pkgs <- c(pkgs,c(,'bookdown', 'broom', 'coda', 'conflicted', 'corrplot', 'docopt'));
          pkgs <- c(pkgs, c('dplyr', 'flextable', 'forcats', 'ggbeeswarm', 'ggfortify', 'ggplot2'));
          pkgs <- c(pkgs, c('ggpubr', 'ggrepel', 'ggridges', 'glue', 'htmlwidgets', 'knitr'));
          pkgs <- c(pkgs, c('limma', 'lme4', 'lmerTest', 'magrittr', 'multcomp', 'pROC'));
          pkgs <- c(pkgs, c('pheatmap', 'plotly', 'plyr', 'progress', 'purrr', 'readr'));
          pkgs <- c(pkgs, c('readxl', 'rlang', 'rmarkdown', 'testthat', 'tibble', 'tidyr'));
          pkgs <- c(pkgs, c('tidyverse', 'vsn', 'yaml', 'writexl')) ;
          lapply(pkgs, function(i){if (!i %in% installed.packages()){BiocManager::install(i)}}); 
        shell: Rscript {0}
      - name: Cache R packages
        id: cache-rpkgs-cran-bioc
        uses: actions/cache@v2
        with:
            path:  ~/work/_temp/Library/
            key: ${{ runner.os }}-RpkgsV3-prolfqua

      - name: Install prolfqua
        run: |
          remotes::install_gitlab("wolski/prolfquaData", host="gitlab.bfabric.org");
          remotes::install_github("protViz/prozor");
        shell: Rscript {0}

      - name: rcmdcheck::rcmdcheck
        run: rcmdcheck::rcmdcheck(error_on = "never", check_dir = "check")
        shell: Rscript {0}

      - name: List files in home directory
        run: find $R_LIBS_SITE -type f > files.txt
      - uses: actions/upload-artifact@v2
        with:
            name: files
            path: files.txt
            if-no-files-found: warn

      - uses: actions/upload-artifact@v2
        with:
            name: prolfqua CI Rcheck directory
            path: check/prolfqua.Rcheck
            if-no-files-found: warn

#      - uses: actions/upload-artifact@v2
#        with:
#            name: R_LIBS_SITE directory
#            path: /home/runner/work/_temp/Library/
#            if-no-files-found: warn
